/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppJournalsRouteImport } from './routes/app.journals'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppBankRouteImport } from './routes/app.bank'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalsRoute = AppJournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bank': typeof AppBankRoute
  '/app/bills': typeof AppBillsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/journals': typeof AppJournalsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bank': typeof AppBankRoute
  '/app/bills': typeof AppBillsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/journals': typeof AppJournalsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bank': typeof AppBankRoute
  '/app/bills': typeof AppBillsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/journals': typeof AppJournalsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/suppliers': typeof AppSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bank'
    | '/app/bills'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/journals'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bank'
    | '/app/bills'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/journals'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/suppliers'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bank'
    | '/app/bills'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/journals'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journals': {
      id: '/app/journals'
      path: '/journals'
      fullPath: '/app/journals'
      preLoaderRoute: typeof AppJournalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bank': {
      id: '/app/bank'
      path: '/bank'
      fullPath: '/app/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBankRoute: typeof AppBankRoute
  AppBillsRoute: typeof AppBillsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppJournalsRoute: typeof AppJournalsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBankRoute: AppBankRoute,
  AppBillsRoute: AppBillsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppJournalsRoute: AppJournalsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
